### ISSUE TITLE
led_set() does not accept 0 for r, g or b

### ISSUE THREAD

**Issue by DurandA** [NordicSemiconductor/Nordic-Thingy52-Nodejs#3]
Due to `if (!data || !data.r || !data.g || !data.b)` [value check](https://github.com/NordicPlayground/Nordic-Thingy52-Nodejs/blob/81aba3d6292157d1bed04a7a91cfc5e82e5b0157/lib/thingy.js#L379) for `led_set()`, passing *data* with r, g or b as 0 trigger an error:

```
led = {r: 255, g: 0, b: 0}
thingy.led_set(led, function(error){
            console.log('LED color change: ' + error);
});
```
This problem is also present in other places of the library. I'm willing to make a pull request, do you prefer `hasOwnProperty`, `in` or `try...catch`?

**Comment by joakimtoe** [comment]
Thanks for the feedback @DurandA. This should now be fixed in the latest version. [v1.0.4.](https://github.com/NordicPlayground/Nordic-Thingy52-Nodejs/commit/5f92f13b49528b2aa80a717118d631cb5a262cb6)
